// <auto-generated />
using System;
using Infrastructure.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Entities.GroupEntity", b =>
                {
                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpecialtyId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Domain.Model.Entities.SpecialtyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialty");
                });

            modelBuilder.Entity("Domain.Model.Entity.DayScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("Date_Index");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("Group_Index");

                    b.ToTable("DaySchedule");
                });

            modelBuilder.Entity("Domain.Model.Entity.LessonEntity", b =>
                {
                    b.Property<Guid>("Groupid")
                        .HasColumnType("uuid");

                    b.Property<string>("Classroom1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Classroom2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Subject1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Teacher1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Teacher2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Groupid");

                    b.HasIndex("Teacher1", "Teacher2")
                        .HasDatabaseName("Teachers_Index");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Domain.Model.Entity.TeacherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Domain.Model.Entities.GroupEntity", b =>
                {
                    b.HasOne("Domain.Model.Entities.SpecialtyEntity", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Domain.Model.Entity.LessonEntity", b =>
                {
                    b.HasOne("Domain.Model.Entity.DayScheduleEntity", "daySchedule")
                        .WithMany()
                        .HasForeignKey("Groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("daySchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
